version: 1.0
services:
app:
  runtime: python
  runtime-version: 3.10
  build:
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt

    environment:
      - AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS }}
      - AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET }}
      - AWS_ACCESS=${{ secrets.AWS_ACCESS }}
      - AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET }}
    command: uvicorn app:app --host 0.0.0.0 --port 8080
    healthCheck:
      path: /health
      interval: 5 seconds
      timeout: 2 seconds
      healthyThreshold: 2
      unhealthyThreshold: 5
