name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  AWS_ACCESS: ${{ secrets.AWS_ACCESS }}
  AWS_SECRET: ${{ secrets.AWS_SECRET }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: make install

    - name: lint
      run: make lint

    - name: tests
      run: make check
